application:
  config:
    employee-url: http://localhost:8082/employee

spring:
  application:
    name: department-service

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0