eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: employee-service

server:
  port: 8082

management:
  tracing:
    sampling:
      probability: 1.0

