eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: department-service
          uri: http://localhost:8081
          predicates:
            - Path=/department/**
        - id: employee-service
          uri: http://localhost:8082
          predicates:
            - Path=/employee/**

management:
  tracing:
    sampling:
      probability: 1.0